# config/services.yaml
parameters:
    minio.endpoint: 'http://localhost:9000'
    minio.region: 'us-east-1'
    minio.key: 'LnXqkCZEYT9kJjWO95JK'
    minio.secret: 'FCpVCQ5iLB1fvi4qu142vLo5ROphoOV87G9x7mFY'
    minio.bucketName: 'mybucket'


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\FileController:
        arguments:
            $defaultStorage: '@League\Flysystem\FilesystemOperator'

    # client MinIO
    app.minio_client:
        class: Aws\S3\S3Client
        factory: ['Aws\S3\S3Client', 'factory']
        arguments:
            - version: 'latest'
              region: 'us-east-1'
              endpoint: 'http://localhost:9000'  
              use_path_style_endpoint: true
              credentials:
                  key: 'LnXqkCZEYT9kJjWO95JK'      
                  secret: 'FCpVCQ5iLB1fvi4qu142vLo5ROphoOV87G9x7mFY'   

    # FilesystemOperator avec  l adaptateur MinIO
    League\Flysystem\FilesystemOperator:
        class: League\Flysystem\Filesystem
        arguments:
            - '@League\Flysystem\AwsS3V3\AwsS3V3Adapter'

    League\Flysystem\AwsS3V3\AwsS3V3Adapter:
        class: League\Flysystem\AwsS3V3\AwsS3V3Adapter
        arguments:
            $client: '@app.minio_client'
            $bucket: 'mybucket'  
            $prefix: 'uploads'   
    
    App\Controller\DownloadController:
        autowire: true
        autoconfigure: true
        
